### PR TITLE
refactor: add support for nuxt 3/nuxt bridge

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
This PR enables this module to work for Nuxt Bridge & Nuxt 3.
Resoles #75, #69, #78 

## 🔥 Notable changes

- Uses `@nuxt/module-builder` to build module
- Refactor structure using `@nuxt/kit`
- We have two configurations (vite/webpack)

## TODO later on
- [x] Re-enable e2e test suite (https://github.com/nuxt/nuxt.js/issues/13372)
- [x] Update readme
- [ ] Errors/warnings only appear in the terminal, must appear in the browser (overlay)

### CODE REVIEW

**Comment by duboiss** [comment]
Hey @ricardogobbosouza , when do you plan to merge / release this? Thanks

**Comment by gkweb** [comment]
Can't wait for this to go through! Will fix having to hack a nuxt bridge migration I'm doing. Thanks heaps.

**Comment by JuanxCursed** [comment]
+1

**Comment by Saran010** [comment]
+1

**Comment by bf** [comment]
This would be highly appreciated. What is missing to complete this?

**Comment by jonorozcoc** [comment]
Any new on this? @ricardogobbosouza

**Comment by ricardogobbosouza** [comment]
I will get back to work on this module now that we have a more stable version of nuxt v3

**Comment by sctouch** [comment]
Nuxt 3 just release stable yesterday, so it should be ready to start all over again, thanks for your effort.

**Comment by mukundshah** [comment]
Hi,
Is this PR mergeable yet?

**Comment by ricardogobbosouza** [comment]
Hi @mukundshah 
It's not finished yet

**Comment by vorjyga** [comment]
Any news?

**Comment by andrevferreiraa** [comment]
Any news on this?

**Comment by MartinX3** [comment]
@ricardogobbosouza Using nuxt 2 and nuxt bridge results in the following error

```
 FATAL  nuxt.hooks.hookOnce is not a function                                                                                                                                     19:26:38

  at setup (node_modules/.pnpm/@nuxtjs+eslint-module@4.0.0_47imvc6hy6dc2w6gfpmnntc3hq/node_modules/@nuxtjs/eslint-module/dist/module.mjs:34:16)
  at ModuleContainer.normalizedModule (node_modules/.pnpm/@nuxt+kit@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async ModuleContainer.addModule (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:167:20)
  at async ModuleContainer.ready (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:36:5)
  at async Nuxt._init (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:342:5)


 ERROR  Cannot start nuxt:  nuxt.hooks.hookOnce is not a function                                                                                                                 19:26:38

  at setup (node_modules/.pnpm/@nuxtjs+eslint-module@4.0.0_47imvc6hy6dc2w6gfpmnntc3hq/node_modules/@nuxtjs/eslint-module/dist/module.mjs:34:16)
  at ModuleContainer.normalizedModule (node_modules/.pnpm/@nuxt+kit@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async ModuleContainer.addModule (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:167:20)
  at async ModuleContainer.ready (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:36:5)
  at async Nuxt._init (node_modules/.pnpm/@nuxt+core@2.16.2/node_modules/@nuxt/core/dist/core.js:342:5)
```

I already removed the node_modules and reinstalled everything again with pnpm.

**Comment by ricardogobbosouza** [comment]
Fixed https://github.com/nuxt-community/eslint-module/pull/80

**Comment by ricardogobbosouza** [comment]
@Deckluhm 
I will add a readme note.

And yes, v4 needs the bridge

**Pull request merged**
