### PR TITLE
fix: bridge compatibility

### PR DESCRIPTION
**Pull request by ricardogobbosouza**

### CODE REVIEW

**Comment by MartinX3** [comment]
@ricardogobbosouza 
```
 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'tap')                                                                                                  11:27:49

  at node_modules/.pnpm/eslint-webpack-plugin@4.0.0_p72rhxqnkxdgq5hcokxg4t4deu/node_modules/eslint-webpack-plugin/dist/index.js:120:42
  at SyncHook.eval [as call] (eval at create (node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:87:1)
  at SyncHook.lazyCompileHook (node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/Hook.js:154:20)
  at Compiler.newCompilation (node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/Compiler.js:631:26)
  at node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/Compiler.js:667:29
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/Hook.js:154:20)
  at Compiler.compile (node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/Compiler.js:662:28)
  at node_modules/.pnpm/webpack@4.46.0/node_modules/webpack/lib/Watching.js:77:18
  at _next1 (eval at create (node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
```

**Comment by argoyle** [comment]
Any update on the problem @MartinX3 reported above?

**Comment by MartinX3** [comment]
@argoyle I deactivated this modul and wait for a response by @ricardogobbosouza

**Comment by xel1045** [comment]
Nuxt Bridge use Webpack 4 under the hood, so `eslint-webpack-plugin@^2.0.0` should be used, but `^4.0.1` is specified by `@nuxtjs/eslint-module`.

As a workaround, you could add a resolution to your `package.json` to force v2 to be installed:

```
    "resolutions": {
        "eslint-webpack-plugin": "^2.0.0"
    },
```

**Pull request merged**
